#172 - build version in footer
blumilksoftware/toby pull request #179
Opened 2022-07-05 11:40 UTC by kamilniemczycki

This should close #172

**Required for next deployment:**

1. Enabling heroku labs in heroku-cli:
   
   ```shell
   heroku labs:enable runtime-dyno-metadata -a <app name>
   ```
3. Adding a variable in the heroku settings ``GITHUB_REPO_URL=https://github.com/blumilksoftware/toby`` or use the command in heroku-cli:
   
   ```shell
   heroku config:set GITHUB_REPO_URL=https://github.com/blumilksoftware/toby -a <app name>
   ```

**Presentation:**

![Login page](https://user-images.githubusercontent.com/1353655/177318646-a30d7c23-576a-4acd-b2db-7eb6d7a33f1c.png)

![Dashboard](https://user-images.githubusercontent.com/1353655/177319055-7cddddc1-76d6-41c3-a62b-5083e3adb3a6.png)

2022-07-05 12:09 UTC, krzysztofrewak requested changes

2022-07-05 12:09 UTC, krzysztofrewak commented on app/Infrastructure/Http/Middleware/HandleInertiaRequests.php
> +        return fn() => [
```suggestion
        return fn(): array => [
```

2022-07-08 04:43 UTC, Baakoma approved these changes

2022-07-08 10:59 UTC, EwelinaLasowy approved these changes

2022-07-11 06:52 UTC, krzysztofrewak approved these changes

2022-07-11 08:42 UTC, merged