#152 - new design for dashboard
blumilksoftware/toby pull request #183
Opened 2022-07-07 10:35 UTC by kamilniemczycki

This should close #152 

**Changes:**
1. The dashboard has been redesigned
2. Calendar widget added
3. The behaviour of statuses depending on the limit held has been changed.

**Presentation:**

https://user-images.githubusercontent.com/1353655/177753265-badcf032-e32d-45e7-a448-f91217705e9c.mp4

2022-07-07 12:58 UTC, krzysztofrewak reviewed
It would be great if this week/month selection would be remembered by the browser.

2022-07-08 05:02 UTC, Baakoma submitted a review, later dismissed

2022-07-11 06:48 UTC, EwelinaLasowy commented on app/Domain/UserVacationStatsRetriever.php
> +    public function hasVacationDaysLimit(User $user, YearPeriod $yearPeriod): bool
The method above `getVacationDaysLimit` looks almost exactly the same as this method. The only difference is return type. We shouldn't duplicate code, but think how to use existing code.

2022-07-11 12:21 UTC, EwelinaLasowy submitted a review, later dismissed

2022-07-12 07:29 UTC, krzysztofrewak requested changes
Maybe we should rename all "home office" occurences to "remote work"?

2022-07-12 07:29 UTC, krzysztofrewak commented on app/Domain/UserVacationStatsRetriever.php
> +            ?->hasVacation() ?? false;
```suggestion
            ->first()?->hasVacation() ?? false;
```

This is more readable, I think.

2022-07-12 07:29 UTC, krzysztofrewak commented on resources/js/Shared/Widgets/HomeOfficeList.vue
> +          Nikt nie pracuje z domu
```suggestion
          Nikt nie pracuje zdalnie
```

You don't need to sit at home during remote work. ;)

2022-07-13 08:59 UTC, krzysztofrewak commented
`HomeOffice` is still visible in components names.

2022-07-13 11:03 UTC, EwelinaLasowy commented
After deploy this command `php artisan toby:rename-home-office-to-remote-work`should be run.

2022-07-13 11:42 UTC, krzysztofrewak approved these changes
Can I deploy it after this PR would be merged? I would not like to foget about running this command.

2022-07-13 11:43 UTC, EwelinaLasowy commented
> Can I deploy it after this PR would be merged? I would not like to foget about running this command.

Yes, no problem.

2022-07-13 11:44 UTC, Baakoma approved these changes

2022-07-13 11:47 UTC, merged