#337 -  add dates to medical exams and ohs
blumilksoftware/toby pull request #338
Opened 2023-08-31 12:23 UTC by EwelinaSkrzypacz

This should close #337.

![image](https://github.com/blumilksoftware/toby/assets/56546832/8bdee778-3d01-40f6-a073-b4b483aedb59)

![image](https://github.com/blumilksoftware/toby/assets/56546832/e35a4a09-cdcd-4159-8196-93be47a942a3)

2023-09-04 11:15 UTC, krzysztofrewak requested changes

2023-09-04 11:15 UTC, krzysztofrewak commented on app/Eloquent/Models/Profile.php
> + * @property Carbon $last_medical_exam_date
What about nullables?

2023-09-04 11:15 UTC, krzysztofrewak commented on app/Eloquent/Models/Profile.php
> + * @property Carbon $next_ohs_training_date
```suggestion
 * @property ?Carbon $last_medical_exam_date
 * @property ?Carbon $next_medical_exam_date
 * @property ?Carbon $last_ohs_training_date
 * @property ?Carbon $next_ohs_training_date
```

2023-09-04 11:15 UTC, krzysztofrewak commented on app/Infrastructure/Console/Kernel.php
> +        $schedule->command(SendNotificationAboutUpcomingAndOverdueMedicalExams::class)->monthlyOn(1, "08:00");
```suggestion
        $schedule->command(SendNotificationAboutUpcomingAndOverdueMedicalExams::class)->monthlyOn(1, "08:00")->onOneServer();
```

Please change it in other command too: https://laravel.com/docs/10.x/scheduling#running-tasks-on-one-server

2023-09-04 11:15 UTC, krzysztofrewak commented on database/migrations/2023_11_29_142131_add_dates_of_medical_exams_and_ohs_in_profiles_table.php
> +            $table->date("next_ohs_training_date")->nullable();
```suggestion
            $table->date("last_medical_exam_date")->nullable()->default(null);
            $table->date("next_medical_exam_date")->nullable()->default(null);
            $table->date("last_ohs_training_date")->nullable()->default(null);
            $table->date("next_ohs_training_date")->nullable()->default(null);
```

2023-09-05 07:04 UTC, krzysztofrewak approved these changes

2023-09-05 08:17 UTC, Baakoma approved these changes

2023-09-05 08:18 UTC, merged