#250 - add command for giving keys to office and taking them
blumilksoftware/toby pull request #342
Opened 2023-09-05 08:17 UTC by EwelinaSkrzypacz

This should close #250.

2023-09-08 08:26 UTC, krzysztofrewak requested changes

2023-09-08 08:26 UTC, krzysztofrewak commented on app/Infrastructure/Slack/Handlers/LeaveKeysInOffice.php
> +        /** @var Key $key */
```suggestion
        /** @var Key|null $key */
```

2023-09-08 08:26 UTC, krzysztofrewak commented on app/Infrastructure/Slack/Handlers/TakeKeysFromOffice.php
> +        /** @var Key $key */
```suggestion
        /** @var Key|null $key */
```

2023-09-08 08:26 UTC, krzysztofrewak commented on app/Infrastructure/Slack/Handlers/LeaveKeysInOffice.php
> +    protected $signature = "toby klucze:biuro:zostaw";
Why in Polish?

2023-09-25 07:45 UTC, EwelinaSkrzypacz commented on app/Infrastructure/Slack/Handlers/LeaveKeysInOffice.php
> +    protected $signature = "toby klucze:biuro:zostaw";
Because we have all commands in Polish.

2023-09-25 08:04 UTC, krzysztofrewak approved these changes

2023-09-25 09:52 UTC, Baakoma approved these changes

2023-09-25 10:23 UTC, merged