#235 -e-mail notification for administrative approval to fill benefits
blumilksoftware/toby pull request #344
Opened 2023-09-05 11:37 UTC by EwelinaSkrzypacz

This should close #235.

![image](https://github.com/blumilksoftware/toby/assets/56546832/b61833b9-d98b-426d-8a8d-54745b44f4e0)

2023-09-08 08:23 UTC, krzysztofrewak requested changes

2023-09-08 08:23 UTC, krzysztofrewak commented on app/Domain/Notifications/BenefitsReportCreationNotification.php
> +        );
```suggestion
        $url = route("assigned-benefits.index");
```

2023-09-25 08:04 UTC, krzysztofrewak approved these changes

2023-09-25 08:04 UTC, krzysztofrewak commented
Probably you should wait for #353 with that.

2023-09-26 06:13 UTC, Baakoma approved these changes

2023-09-26 06:13 UTC, merged