#452 - user profile cleaning
blumilksoftware/toby pull request #459
Opened 2024-07-04 12:37 UTC by kamilpiech97

Connected with #452.
Removed form user profile model/table not used fields.
Updated seeders and tests.
Added cache for user history stuff.

2024-07-22 11:57 UTC, krzysztofrewak requested changes

2024-07-22 11:57 UTC, krzysztofrewak commented on app/Observers/UserHistoryObserver.php
> +        CacheQuery::forget("userHistories{$userHistory->user->id}");
```suggestion
        CacheQuery::forget("user:history:{$userHistory->user->id}");
```
I think that would be easier to manage.

2024-07-22 11:57 UTC, krzysztofrewak commented on database/migrations/2024_07_04_130731_cleaning_fields_in_profiles_table.php
> +            $table->date("employment_date")->nullable();
No default value?

2024-07-22 12:00 UTC, kamilpiech97 commented on app/Observers/UserHistoryObserver.php
> +        CacheQuery::forget("userHistories{$userHistory->user->id}");
Should I update other cache keys?

2024-07-22 12:25 UTC, kamilpiech97 commented on database/migrations/2024_07_04_130731_cleaning_fields_in_profiles_table.php
> +            $table->date("employment_date")->nullable();
added

2024-07-22 12:38 UTC, EwelinaSkrzypacz approved these changes

2024-07-23 05:37 UTC, EwelinaSkrzypacz approved these changes

2024-07-23 06:34 UTC, krzysztofrewak approved these changes

2024-07-23 06:43 UTC, merged